// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFLwDYwt0JdC6QWYZZgYNC2md1WJL3kw',
    appId: '1:435117422124:web:966cd4083444115c900389',
    messagingSenderId: '435117422124',
    projectId: 'dj-catch-7d079',
    authDomain: 'dj-catch-7d079.firebaseapp.com',
    storageBucket: 'dj-catch-7d079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbC126TJpHkfY70ZG99KQHZfM5qsF50o',
    appId: '1:435117422124:ios:0f9f39c0bf6ae512900389',
    messagingSenderId: '435117422124',
    projectId: 'dj-catch-7d079',
    storageBucket: 'dj-catch-7d079.firebasestorage.app',
    iosBundleId: 'com.example.djCatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClbC126TJpHkfY70ZG99KQHZfM5qsF50o',
    appId: '1:435117422124:ios:0f9f39c0bf6ae512900389',
    messagingSenderId: '435117422124',
    projectId: 'dj-catch-7d079',
    storageBucket: 'dj-catch-7d079.firebasestorage.app',
    iosBundleId: 'com.example.djCatch',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ylpbhZNm5leS-vqYwdp4tMp9TRWN2cg',
    appId: '1:435117422124:android:be1d8cf5a83c2163900389',
    messagingSenderId: '435117422124',
    projectId: 'dj-catch-7d079',
    storageBucket: 'dj-catch-7d079.firebasestorage.app',
  );

}